"""
feature_registry.py — Canonical list of model features and target mappings.

FEATURE_COLUMNS defines every numeric column used as model input.
TARGET_COLUMNS maps user-facing target names to DataFrame column names.
"""

FEATURE_COLUMNS = [
    "home_score_lag_1",
    "away_score_lag_1",
    "home_margin_lag_1",
    "away_margin_lag_1",
    "home_score_roll_3",
    "away_score_roll_3",
    "home_margin_roll_3",
    "away_margin_roll_3",
    "home_rest_days",
    "away_rest_days",
    "market_spread",
    "market_total_line",
    "market_moneyline_home",
    "market_moneyline_away",
    "market_implied_prob_home",
    "market_implied_prob_away",
    "market_moneyline_delta",
    "home_team_encoded",
    "away_team_encoded",
    "is_tournament_game",
    "round_order",
    "seed_home",
    "seed_away",
    "seed_diff",
    "home_is_higher_seed",
    "seed_matchup_bucket",
    "upset_band",
    "home_seed_hist_win_pct",
    "away_seed_hist_win_pct",
    "home_seed_hist_upset_win_pct",
    "away_seed_hist_upset_win_pct",
    "is_postseason_game",
    "postseason_round_order",
    "postseason_round_tier",
    "playoff_experience_home",
    "playoff_experience_away",
    "championship_game_flag",
    # NFL context
    "week_number",
    "is_indoor",
    "surface_is_grass",
    "rest_advantage",
    "is_short_week",
    # NFL game stats (rolling 3-game averages)
    "home_total_yards_roll3",
    "away_total_yards_roll3",
    "home_passing_yards_roll3",
    "away_passing_yards_roll3",
    "home_rushing_yards_roll3",
    "away_rushing_yards_roll3",
    "home_turnovers_roll3",
    "away_turnovers_roll3",
    "home_third_down_pct_roll3",
    "away_third_down_pct_roll3",
    "home_red_zone_pct_roll3",
    "away_red_zone_pct_roll3",
    "home_sacks_allowed_roll3",
    "away_sacks_allowed_roll3",
    "home_possession_secs_roll3",
    "away_possession_secs_roll3",
    "turnover_margin_roll3",
    "yards_advantage_roll3",
    # NFL standings
    "home_win_pct",
    "away_win_pct",
    "win_pct_diff",
    "home_streak",
    "away_streak",
    "home_home_win_pct",
    "away_away_win_pct",
    # NFL injuries
    "home_players_out",
    "away_players_out",
    "home_skill_out",
    "away_skill_out",
    "home_qb_out",
    "away_qb_out",
    "home_players_doubtful",
    "away_players_doubtful",
    "injury_advantage",
    # NCAA MBB context
    "neutral_site",
    "is_conference_game",
    "home_conf_win_pct",
    "away_conf_win_pct",
    "conf_win_pct_diff",
    "away_road_win_pct",
    # NCAA MBB game stats (rolling 3-game averages)
    "home_fg_pct_roll3",
    "away_fg_pct_roll3",
    "home_three_pt_pct_roll3",
    "away_three_pt_pct_roll3",
    "home_ft_pct_roll3",
    "away_ft_pct_roll3",
    "home_total_rebounds_roll3",
    "away_total_rebounds_roll3",
    "home_off_rebounds_roll3",
    "away_off_rebounds_roll3",
    "home_assists_roll3",
    "away_assists_roll3",
    "home_turnovers_mbb_roll3",
    "away_turnovers_mbb_roll3",
    "home_fast_break_points_roll3",
    "away_fast_break_points_roll3",
    "home_points_in_paint_roll3",
    "away_points_in_paint_roll3",
    "rebound_margin_mbb_roll3",
    "turnover_margin_mbb_roll3",
    # NCAA MBB BPI & ratings
    "home_bpi",
    "away_bpi",
    "bpi_diff",
    "home_bpi_offense",
    "away_bpi_defense",
    "bpi_offense_vs_defense",
    "home_sor",
    "away_sor",
    "sor_diff",
    # NCAA MBB poll rankings
    "home_ap_rank",
    "away_ap_rank",
    "rank_advantage",
    "home_is_ranked",
    "away_is_ranked",
    # NCAA MBB game predictor (BPI pre-game win probability)
    "home_pred_win_pct",
    "home_pred_mov",
    "matchup_quality",
]

TARGET_COLUMNS = {
    "home_win": "target_home_win",
    "cover_home": "target_cover_home",
    "total_over": "target_total_over",
}
